bot:
  token: BOT_TOKEN
  env: true
  
  prefix:
    when_mentioned: true
    values: 
      - '?'
  
  errors:
    enabled: true
    private: false

    command_not_found: false

  status:
    webhook_url: "STATUS_WEBHOOK"
    env: true 