name: Discord Bot
on:
  push:
    branches: [ master ]
  schedule:
    - cron: "0 */4 * * *"

concurrency: 
  group: "Marl"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checking out repository content
        uses: actions/checkout@v2

      - name: Setting up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install requirements
        run: |
          pip install --upgrade pip
          pip install -r "requirements.txt"
      
      - name: Setup MarlDB
        run: |
          git clone  "marl-db"

      - name: Run Bot code
        run: |
          python "me.py"
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          STATUS_WEBHOOK: ${{ secrets.STATUS_WEBHOOK }}

      - uses: webiny/action-post-run@2.0.1
        id: "changes-to-db"
        with:
          run: |
            cd "marl-db"
            git config user.name "MarlServer"
            git config user.email "null"
            git add "marl-db.json"
            git commit -m "Chore: DB update on restart."
            git push --force
